// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EnergyDataPoint struct {
	Value        int    `json:"value"`
	Building     string `json:"building"`
	DateTimeUnix int    `json:"dateTimeUnix"`
	Unit         string `json:"unit"`
	Type         string `json:"type"`
}
